# Modified by two-barrels in 2026 for ARI v6 modernization.
# SPDX-License-Identifier: Apache-2.0

all: false
dir: "client/arimocks"
filename: "{{.InterfaceName}}.go"
structname: "{{.InterfaceName}}"
pkgname: "arimocks"
template-data:
  unroll-variadic: true
packages:
  github.com/two-barrels/ari/v6:
    config:
      all: true
